name: "Version Extraction Debug"

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run debug script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FORMULA_NAME="ffmpeg-lgpl"
          FORMULA_FILE="ffmpeg-lgpl.rb"
          
          # バージョンとリビジョンを抽出するロジック
          FORMULA_VERSION=$(grep -E '^\s*version\s+"[^"]+"' "$FORMULA_FILE" | sed -E 's/.*"([^"]+)".*/\1/')
          FORMULA_REVISION=$(grep -E '^\s*revision\s+[0-9]+' "$FORMULA_FILE" | sed -E 's/.*revision\s+([0-9]+)/\1/')
          
          if [[ -z "$FORMULA_REVISION" ]]; then
            FORMULA_REVISION="0"
          fi
          
          if [ "$FORMULA_REVISION" == "0" ]; then
            RELEASE_TAG="v$FORMULA_VERSION"
          else
            RELEASE_TAG="v${FORMULA_VERSION}_${FORMULA_REVISION}"
          fi
          
          OS_TAG="sonoma" # macOS-14のシミュレーション
          ARCH_TAG="arm64"
          
          FILE_NAME="${FORMULA_NAME}-${FORMULA_VERSION}_${FORMULA_REVISION}.${ARCH_TAG}_${OS_TAG}.bottle.tar.gz"
          
          FILE_NAME=$(echo "$FILE_NAME" | sed 's/--/-/g')
          
          echo "FORMULA_VERSION: $FORMULA_VERSION"
          echo "FORMULA_REVISION: $FORMULA_REVISION"
          echo "RELEASE_TAG: $RELEASE_TAG"
          echo "FILE_NAME: $FILE_NAME"
