name: "Version Extraction Debug"

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run debug script
        run: |
          FORMULA_NAME="ffmpeg-lgpl"
          FORMULA_FILE="ffmpeg-lgpl.rb"
          
          # 修正したバージョン抽出ロジック
          FORMULA_VERSION=$(grep -E '^\s*version\s+' "$FORMULA_FILE" | awk '{print $2}' | tr -d '"')
          
          # 修正したリビジョン抽出ロジック
          FORMULA_REVISION=$(grep -E '^\s*revision\s+' "$FORMULA_FILE" | awk '{print $2}')
          
          # リビジョンが取得できない場合は0と見なす
          if [[ -z "$FORMULA_REVISION" ]]; then
            FORMULA_REVISION="0"
          fi
          
          # 結果を出力して確認
          echo "### Debugging Output ###"
          echo "FORMULA_VERSION: '$FORMULA_VERSION'"
          echo "FORMULA_REVISION: '$FORMULA_REVISION'"
