name: "Release Bottles"

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: brew update --auto-update
          
      - name: Tap this repository
        run: brew tap lgpl-dev/ffmpeg-lgpl

      - name: Build and bottle formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: brew bottle --force --json --no-rebuild ffmpeg-lgpl

      - name: Release bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: brew release-pr --bottle --no-browse ffmpeg-lgpl.json
