- name: Build bottle and get info
        id: bottle
        run: |
          # brew bottle を実行し、JSONファイルとボトルファイルが自動生成される
          brew bottle --json --no-rebuild ffmpeg-lgpl

          # 生成されたJSONファイルの名前を特定
          JSON_FILE=$(ls -1 *.json | head -n 1)
          
          # 生成されたボトルファイルの名前を特定
          BOTTLE_FILENAME=$(ls -1 *.tar.gz | head -n 1)

          # JSONからバージョンを抽出
          FORMULA_VERSION=$(jq -r '.[].formula.pkg_version' "$JSON_FILE")

          # 後続のステップで利用できるよう、出力として設定
          echo "FORMULA_VERSION=$FORMULA_VERSION" >> $GITHUB_OUTPUT
          echo "BOTTLE_FILENAME=$BOTTLE_FILENAME" >> $GITHUB_OUTPUT
          echo "JSON_FILENAME=$JSON_FILE" >> $GITHUB_OUTPUT
