name: Build and Upload Bottle

on:
  workflow_dispatch:
    inputs:
      formula_name:
        description: 'Formula to bottle (e.g., ffmpeg-lgpl)'
        required: true
        type: string
      tag_name:
        description: 'Tag name for the new release'
        required: true
        type: string

jobs:
  build_and_upload_bottle:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle
        run: |
          brew bottle --json ${{ github.event.inputs.formula_name }}

      - name: Get paths of bottle and JSON files
        id: get_paths
        run: |
          BOTTLE_FILE=$(find . -name "*.bottle.tar.gz")
          JSON_FILE=$(find . -name "*.json")
          echo "BOTTLE_PATH=$BOTTLE_FILE" >> $GITHUB_OUTPUT
          echo "JSON_PATH=$JSON_FILE" >> $GITHUB_OUTPUT
          echo "BOTTLE_NAME=$(basename $BOTTLE_FILE)" >> $GITHUB_OUTPUT
          echo "JSON_NAME=$(basename $JSON_FILE)" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.tag_name }} Bottle
          draft: false
          prerelease: false

      - name: Upload bottle asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_paths.outputs.BOTTLE_PATH }}
          asset_name: ${{ steps.get_paths.outputs.BOTTLE_NAME }}
          asset_content_type: application/octet-stream
      
      - name: Upload JSON asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_paths.outputs.JSON_PATH }}
          asset_name: ${{ steps.get_paths.outputs.JSON_NAME }}
          asset_content_type: application/json
