name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-bottles:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew
        id: cache-homebrew
        uses: Homebrew/actions/cache@master

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: brew install aom fontconfig freetype harfbuzz jpeg-xl libass libssh libvmaf libvorbis openjpeg opus tesseract webp xz

      - name: Build bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: brew test-bot --only-json-tab --ci-pr-labels=''
        
      - name: Upload bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          brew tap-new --no-commit --force "${{ github.repository }}"
          brew pr-upload --no-pr
