name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-bottles:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@v4
      
      - name: Install dependencies
        run: brew install aom fontconfig freetype harfbuzz jpeg-xl libass libssh libvmaf libvorbis openjpeg opus tesseract webp xz

      - name: Build and upload bottle
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          brew test-bot --only-json-tab --ci-pr-labels=''
          brew pr-upload --no-pr
