name: "Release Bottles"

on:
  workflow_dispatch:

permissions:
  contents: write # リリースを作成・編集する権限を付与

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew, tap, and install formula
        run: |
          brew update --auto-update
          brew tap lgpl-dev/ffmpeg-lgpl
          brew install ffmpeg-lgpl --build-bottle

      - name: Build and bottle formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          brew bottle --json --no-rebuild ffmpeg-lgpl
          
      - name: Create release and upload bottle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BOTTLE_FILE=$(ls ffmpeg-lgpl--*.bottle.tar.gz)
          RELEASE_VERSION="8.0_1" # Formulaのバージョンとリビジョンを正確に指定
          
          # gh CLI を使用してGitHub Releasesを作成
          gh release create v$RELEASE_VERSION \
            --title "ffmpeg-lgpl v$RELEASE_VERSION" \
            --notes "New bottle for ffmpeg-lgpl."
          
          # 作成したリリースにbottleファイルをアップロード
          gh release upload v$RELEASE_VERSION "$BOTTLE_FILE"
